### PR TITLE
Fix compile warnings and simplify tests

### LINKED ISSUE #18: Update tests
We should:
 1. devise a way to disable logs (write to files, in particular) during tests by default, with the possibility of activating them with a parameter or CMake option;
 2. reduce the number of particles.

### PR DESCRIPTION
**Pull request by claudiofantacci**
This PR fixes some compile warnings, like missing overrides and uninitialized boolean values, and significantly reduces test time. To accomplish the latter, a `TEST_LOG_TO_FILE` variable can be set to `ON` or `OFF` (default is `OFF`) during CMake configuration to allow saving filter logs to file.
This is particularly useful for running tests locally, where one would probably want to enable logs to files, or remotely, where one instead wants tests to run fast and is unable to collect logs.
This PR also reduces the number of points used by the particle filters from `10000` to `900`.

Closes #18.

### CODE REVIEW

**Review by xEnVrE — CHANGES_REQUESTED** [review]
LGTM! Thanks :tada:

Just some concerns about some comments in the tests.

File: test/test_KF/main.cpp [hunk 1]
```diff
@@ -54,10 +56,14 @@ class KFSimulation : public GaussianFilter
...
 
-int main()
+int main(int argc, char* argv[])
 {
     std::cout << "Running a KF filter on a simulated target." << std::endl;
-    std::cout << "Data is logged in the test folder with prefix testKF." << std::endl;
+
+    const bool write_to_file = (argc > 1 ? std::string(argv[1]) == "ON" : false);
+    if (write_to_file)
+        std::cout << "Data is logged in the test folder with prefix testSIS." << std::endl;
```
Comment (xEnVrE) [inline test/test_KF/main.cpp]: I think it should be `... with prefix testKF`.

File: test/test_UKF/main.cpp [hunk 2]
```diff
@@ -55,10 +57,14 @@ class UKFSimulation : public GaussianFilter
...
 
-int main()
+int main(int argc, char* argv[])
 {
     std::cout << "Running a UKF filter on a simulated target." << std::endl;
-    std::cout << "Data is logged in the test folder with prefix testUKF." << std::endl;
+
+    const bool write_to_file = (argc > 1 ? std::string(argv[1]) == "ON" : false);
+    if (write_to_file)
+        std::cout << "Data is logged in the test folder with prefix testSIS." << std::endl;
```
Comment (xEnVrE) [inline test/test_UKF/main.cpp]: I think it should be `... with prefix testUKF`.

File: test/test_UPF/main.cpp [hunk 3]
```diff
@@ -101,16 +102,20 @@ class UPFSimulation : public SIS
...
 
-int main()
+int main(int argc, char* argv[])
 {
     std::cout << "Running an unscented particle filter on a simulated target." << std::endl;
-    std::cout << "Data is logged in the test folder with prefix testUPF." << std::endl;
+
+    const bool write_to_file = (argc > 1 ? std::string(argv[1]) == "ON" : false);
+    if (write_to_file)
+        std::cout << "Data is logged in the test folder with prefix testSIS." << std::endl;
```
Comment (xEnVrE) [inline test/test_UPF/main.cpp]: I think it should be `... with prefix testUPF`.

File: test/test_mixed_KF_SUKF/main.cpp [hunk 4]
```diff
@@ -55,11 +57,15 @@ class MixedKFSUKFSimulation : public GaussianFilter
...
 
-int main()
+int main(int argc, char* argv[])
 {
     std::cout << "Running a SUKF filter with KF prediction and SUKF correction on a simulated target." << std::endl;
-    std::cout << "Data is logged in the test folder with prefix testKF_SUKF." << std::endl;
 
+    const bool write_to_file = (argc > 1 ? std::string(argv[1]) == "ON" : false);
+    if (write_to_file)
+        std::cout << "Data is logged in the test folder with prefix testSIS." << std::endl;
```
Comment (xEnVrE) [inline test/test_mixed_KF_SUKF/main.cpp]: I think it should be `... with prefix testKF_SUKF`.

File: test/test_mixed_KF_UKF/main.cpp [hunk 5]
```diff
@@ -55,10 +57,14 @@ class MixedKFUKFSimulation : public GaussianFilter
...
 
-int main()
+int main(int argc, char* argv[])
 {
     std::cout << "Running a UKF filter with KF prediction and UKF correction on a simulated target." << std::endl;
-    std::cout << "Data is logged in the test folder with prefix testKF_UKF." << std::endl;
+
+    const bool write_to_file = (argc > 1 ? std::string(argv[1]) == "ON" : false);
+    if (write_to_file)
+        std::cout << "Data is logged in the test folder with prefix testSIS." << std::endl;
```
Comment (xEnVrE) [inline test/test_mixed_KF_UKF/main.cpp]: I think it should be `... with prefix testKF_UKF`.

File: test/test_mixed_UKF_KF/main.cpp [hunk 6]
```diff
@@ -55,11 +57,15 @@ class MixedUKFKFSimulation : public GaussianFilter
...
 
-int main()
+int main(int argc, char* argv[])
 {
     std::cout << "Running a mixed UKF/KF filter on a simulated target." << std::endl;
-    std::cout << "Data is logged in the test folder with prefix testUKF_KF." << std::endl;
 
+    const bool write_to_file = (argc > 1 ? std::string(argv[1]) == "ON" : false);
+    if (write_to_file)
+        std::cout << "Data is logged in the test folder with prefix testSIS." << std::endl;
```
Comment (xEnVrE) [inline test/test_mixed_UKF_KF/main.cpp]: I think it should be `... with prefix testUKF_KF`.

**Comment by claudiofantacci** [comment]
Ah, the copypaste inanities. Fixing!

File: test/test_mixed_UKF_KF/main.cpp (hunk 6 above)
Comment (claudiofantacci) [reply test/test_mixed_UKF_KF/main.cpp]: Done!

File: test/test_mixed_KF_UKF/main.cpp (hunk 5 above)
Comment (claudiofantacci) [reply test/test_mixed_KF_UKF/main.cpp]: Done!

File: test/test_mixed_KF_SUKF/main.cpp (hunk 4 above)
Comment (claudiofantacci) [reply test/test_mixed_KF_SUKF/main.cpp]: Done!

File: test/test_UPF/main.cpp (hunk 3 above)
Comment (claudiofantacci) [reply test/test_UPF/main.cpp]: Done!

File: test/test_UKF/main.cpp (hunk 2 above)
Comment (claudiofantacci) [reply test/test_UKF/main.cpp]: Done!

File: test/test_KF/main.cpp (hunk 1 above)
Comment (claudiofantacci) [reply test/test_KF/main.cpp]: Done!

**Review by xEnVrE — APPROVED** [review]
